Bundler.require
require 'coltrane/cadence'
require 'coltrane/chord_quality'
require 'coltrane/chord'
require 'coltrane/classic_scales'
require 'coltrane/fret_set'
require 'coltrane/guitar'
require 'coltrane/interval'
require 'coltrane/interval_set'
require 'coltrane/mode'
require 'coltrane/note'
require 'coltrane/note_set'
require 'coltrane/guitar_note'
require 'coltrane/guitar_note_set'
require 'coltrane/pitch'
require 'coltrane/progression'
require 'coltrane/scale'
require 'coltrane/guitar_string'

require 'terminal_input'