#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

require 'paint'
require 'color'
require 'mercenary'
require 'coltrane/commands'

Paint.mode = 0xFFFFFF

Mercenary.program(:Coltrane) do |p|
  p.version Coltrane::VERSION
  p.description <<~DESC
    A music querying interface
    by Pedro Maciel (pedro@pedromaciel.com)

    Check the chat room for project help/discussion/contribution: https://coltrane-ruby.herokuapp.com
  DESC
  p.syntax 'coltrane <subcommand> [options]'

  Coltrane::Commands::Command.subclasses.each do |command|
    command.mercenary_init(p)
  end

  p.command(:about) do |c|
    c.description 'Shows this screen'
    c.action do
      puts p
    end
  end

  p.default_command(:about)
end

