#!/usr/bin/env ruby
# frozen_string_literal: true
$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

require 'coltrane/ui'

module Coltrane
  module UI
    class App < Gambiarra::App
      def setup
        if ENV['COLORTERM'] == 'truecolor'
          Paint.mode = 0xFFFFFF
        else
          Paint.mode = 0
          puts "This terminal doesn't seem to support true color. " \
               "Try something like iTerm2 (for macOS), VTE or Konsole (for linux) or Hyper" \
               " (for Windows) and you'll see the true magic!"
        end
      end
    end
  end
end

Coltrane::UI::App.start(ARGV.join(' '))
